"""aggregate rate components for spread decomposition

Adds benchmark/liquidity/other multiplied by balance to every aggregate grain.
With these, FTP income decomposes exactly into its four rate components at any
rollup, because income = SUM(balance * rate)/36500 and rate is itself a signed
sum of those components. That is what powers the spread waterfall.

Hand-written rather than autogenerated: autogenerate reflects each partition of
ftp_calculation_results separately and proposes dropping their indexes, which
would be an outage on a large table.

Revision ID: 86851de8e2df
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '86851de8e2df'
down_revision: Union[str, None] = '2a1f5c9d8e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = (
    "agg_daily_branch", "agg_daily_product", "agg_daily_branch_product",
    "agg_daily_division", "agg_daily_district", "agg_daily_category",
)
COLUMNS = ("benchmark_x_balance", "liquidity_x_balance", "other_x_balance")


def upgrade() -> None:
    # Aggregates are rebuilt from facts on every run, so a NOT NULL column with
    # a server default is safe here and the tables are small by construction.
    for table in TABLES:
        for col in COLUMNS:
            op.add_column(
                table,
                sa.Column(col, sa.Numeric(20, 6), nullable=False,
                          server_default=sa.text("0")),
            )


def downgrade() -> None:
    for table in TABLES:
        for col in COLUMNS:
            op.drop_column(table, col)
