"""initial schema

Revision ID: c0d0ce0f0e74
Revises: 
Create Date: 2026-09-21 14:52:01.918977
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c0d0ce0f0e74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_daily_branch',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('branch_category', sa.Enum('METRO', 'URBAN', 'SEMI_URBAN', 'RURAL', name='branch_category'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_receivable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_payable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('asset_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('net_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('roi_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('ftp_rate_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('account_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('negative_ftp_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('branch_id', 'business_date', name=op.f('pk_agg_daily_branch'))
    )
    op.create_index(op.f('ix_agg_daily_branch_district_id'), 'agg_daily_branch', ['district_id'], unique=False)
    op.create_index(op.f('ix_agg_daily_branch_division_id'), 'agg_daily_branch', ['division_id'], unique=False)
    op.create_table('agg_daily_branch_product',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_receivable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_payable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('asset_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('net_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('roi_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('ftp_rate_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('account_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('negative_ftp_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('branch_id', 'product_id', 'business_date', name=op.f('pk_agg_daily_branch_product'))
    )
    op.create_table('agg_daily_category',
    sa.Column('branch_category', sa.Enum('METRO', 'URBAN', 'SEMI_URBAN', 'RURAL', name='branch_category'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_receivable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_payable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('asset_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('net_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('roi_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('ftp_rate_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('account_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('negative_ftp_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('branch_category', 'business_date', name=op.f('pk_agg_daily_category'))
    )
    op.create_table('agg_daily_district',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_receivable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_payable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('asset_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('net_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('roi_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('ftp_rate_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('account_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('negative_ftp_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('district_id', 'business_date', name=op.f('pk_agg_daily_district'))
    )
    op.create_index(op.f('ix_agg_daily_district_division_id'), 'agg_daily_district', ['division_id'], unique=False)
    op.create_table('agg_daily_division',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_receivable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_payable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('asset_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('net_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('roi_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('ftp_rate_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('account_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('negative_ftp_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('division_id', 'business_date', name=op.f('pk_agg_daily_division'))
    )
    op.create_table('agg_daily_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('side', sa.Enum('ASSET', 'LIABILITY', name='product_side'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_receivable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_payable', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('asset_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('net_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('roi_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('ftp_rate_x_balance', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('account_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('negative_ftp_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id', 'business_date', name=op.f('pk_agg_daily_product'))
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('maker_id', sa.BigInteger(), nullable=False),
    sa.Column('maker_comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checker_id', sa.BigInteger(), nullable=True),
    sa.Column('checker_comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('checker_id IS NULL OR checker_id <> maker_id', name=op.f('ck_approval_requests_maker_is_not_checker')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index('ix_approval_status', 'approval_requests', ['status', 'submitted_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_username', sa.String(length=80), nullable=True),
    sa.Column('actor_scope', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.LargeBinary(), nullable=True),
    sa.Column('row_hash', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_action_time', 'audit_log', ['action', 'occurred_at'], unique=False)
    op.create_index('ix_audit_actor_time', 'audit_log', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('bank_daily_account_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.Column('account_no', sa.String(length=40), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('raw_int_payable', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('raw_int_receivable', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('raw_roi', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('source_row_no', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=10), server_default=sa.text("'OK'"), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_daily_account_data'))
    )
    op.create_index('ix_bank_daily_batch', 'bank_daily_account_data', ['batch_id'], unique=False)
    op.create_index('ix_bank_daily_key', 'bank_daily_account_data', ['business_date', 'branch_code', 'account_no'], unique=False)
    op.create_table('calculation_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_ref', sa.String(length=40), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('business_date_from', sa.Date(), nullable=False),
    sa.Column('business_date_to', sa.Date(), nullable=False),
    sa.Column('global_config_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('rows_in', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_out', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_runs'))
    )
    op.create_index(op.f('ix_calculation_runs_batch_id'), 'calculation_runs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_calculation_runs_run_ref'), 'calculation_runs', ['run_ref'], unique=True)
    op.create_index('ix_run_dates', 'calculation_runs', ['business_date_from', 'business_date_to'], unique=False)
    op.create_index('ix_run_status', 'calculation_runs', ['status', 'started_at'], unique=False)
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divisions'))
    )
    op.create_index(op.f('ix_divisions_code'), 'divisions', ['code'], unique=True)
    op.create_table('ftp_calculation_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('branch_category', sa.Enum('METRO', 'URBAN', 'SEMI_URBAN', 'RURAL', name='branch_category'), nullable=False),
    sa.Column('account_no', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('side', sa.Enum('ASSET', 'LIABILITY', name='product_side'), nullable=False),
    sa.Column('liability_nature', sa.Enum('DEMAND', 'TIME', name='liability_nature'), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('raw_roi', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('raw_int_payable', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('raw_int_receivable', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('normalized_roi', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('roi_source', sa.Enum('BANK_PROVIDED', 'CALCULATED_FROM_ROI', 'CALCULATED_FROM_INTEREST', name='value_source'), nullable=False),
    sa.Column('customer_interest', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('interest_source', sa.Enum('BANK_PROVIDED', 'CALCULATED_FROM_ROI', 'CALCULATED_FROM_INTEREST', name='value_source'), nullable=False),
    sa.Column('interest_expected', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('interest_variance', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('interest_mismatch', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('benchmark_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('benchmark_source', sa.Enum('PRODUCT_OVERRIDE', 'GLOBAL_DEFAULT', name='rate_source'), nullable=False),
    sa.Column('liquidity_cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('liquidity_source', sa.Enum('PRODUCT_OVERRIDE', 'GLOBAL_DEFAULT', name='rate_source'), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('other_source', sa.Enum('PRODUCT_OVERRIDE', 'GLOBAL_DEFAULT', name='rate_source'), nullable=False),
    sa.Column('global_config_version', sa.Integer(), nullable=False),
    sa.Column('product_config_version', sa.Integer(), nullable=True),
    sa.Column('ftp_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ftp_income', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('asset_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('liability_ftp_profit', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('negative_ftp_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'business_date', name=op.f('pk_ftp_calculation_results')),
    postgresql_partition_by='RANGE (business_date)'
    )
    op.create_index('ix_ftp_branch_date', 'ftp_calculation_results', ['branch_id', 'business_date'], unique=False, postgresql_where=sa.text('is_current'))
    op.create_index('ix_ftp_district_date', 'ftp_calculation_results', ['district_id', 'business_date'], unique=False, postgresql_where=sa.text('is_current'))
    op.create_index('ix_ftp_division_date', 'ftp_calculation_results', ['division_id', 'business_date'], unique=False, postgresql_where=sa.text('is_current'))
    op.create_index('ix_ftp_negative', 'ftp_calculation_results', ['business_date', 'branch_id'], unique=False, postgresql_where=sa.text('is_current AND negative_ftp_flag'))
    op.create_index('ix_ftp_product_date', 'ftp_calculation_results', ['product_id', 'business_date'], unique=False, postgresql_where=sa.text('is_current'))
    op.create_index('ix_ftp_run', 'ftp_calculation_results', ['run_id'], unique=False)
    op.create_index('uq_ftp_results_current_key', 'ftp_calculation_results', ['business_date', 'branch_code', 'account_no'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('global_rate_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_count_basis', sa.Enum('ACT_365', 'ACT_360', name='day_count_basis'), server_default=sa.text("'ACT_365'"), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('benchmark_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('liquidity_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('maker_id', sa.BigInteger(), nullable=True),
    sa.Column('checker_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_global_rate_config_global_period_valid')),
    sa.CheckConstraint('maker_id IS NULL OR checker_id IS NULL OR checker_id <> maker_id', name=op.f('ck_global_rate_config_global_maker_is_not_checker')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_rate_config'))
    )
    op.create_index('ix_global_rate_effective', 'global_rate_config', ['effective_from', 'effective_to'], unique=False)
    op.create_table('login_audit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_audit'))
    )
    op.create_index('ix_login_audit_at', 'login_audit', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_login_audit_username'), 'login_audit', ['username'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('side', sa.Enum('ASSET', 'LIABILITY', name='product_side'), nullable=False),
    sa.Column('liability_nature', sa.Enum('DEMAND', 'TIME', name='liability_nature'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('udf', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("(side = 'LIABILITY' AND liability_nature IS NOT NULL) OR (side = 'ASSET' AND liability_nature IS NULL)", name=op.f('ck_products_liability_nature_matches_side')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_index('ix_products_side_active', 'products', ['side', 'is_active'], unique=False)
    op.create_table('report_downloads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_code', sa.String(length=60), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_downloads'))
    )
    op.create_index('ix_report_downloads_time', 'report_downloads', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_report_downloads_user_id'), 'report_downloads', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('source_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('adapter_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_systems'))
    )
    op.create_index(op.f('ix_source_systems_code'), 'source_systems', ['code'], unique=True)
    op.create_table('staging_account_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('source_row_no', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('branch_code', sa.String(length=10), nullable=True),
    sa.Column('account_no', sa.String(length=40), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('product_code', sa.String(length=40), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('int_payable', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('int_receivable', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('roi', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'OK'"), nullable=False),
    sa.Column('rule_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staging_account_data'))
    )
    op.create_index(op.f('ix_staging_account_data_batch_id'), 'staging_account_data', ['batch_id'], unique=False)
    op.create_index('ix_staging_batch_row', 'staging_account_data', ['batch_id', 'source_row_no'], unique=False)
    op.create_index('ix_staging_batch_status', 'staging_account_data', ['batch_id', 'status'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('udf_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=20), nullable=False),
    sa.Column('field_key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_udf_definitions'))
    )
    op.create_index('uq_udf_entity_key', 'udf_definitions', ['entity', 'field_key'], unique=True)
    op.create_table('upload_exceptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('source_row_no', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.Enum('REJECT', 'WARN', 'INFO', name='exception_severity'), nullable=False),
    sa.Column('rule_code', sa.String(length=10), nullable=False),
    sa.Column('field_name', sa.String(length=40), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_exceptions'))
    )
    op.create_index('ix_exception_batch_rule', 'upload_exceptions', ['batch_id', 'rule_code'], unique=False)
    op.create_index('ix_exception_severity', 'upload_exceptions', ['batch_id', 'severity'], unique=False)
    op.create_index(op.f('ix_upload_exceptions_batch_id'), 'upload_exceptions', ['batch_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('employee_id', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('scope_level', sa.Enum('HO', 'DIVISION', 'DISTRICT', 'BRANCH', name='scope_level'), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_users_employee_id'))
    )
    op.create_index('ix_users_scope', 'users', ['scope_level', 'scope_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('column_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], name=op.f('fk_column_mappings_source_system_id_source_systems')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_column_mappings'))
    )
    op.create_index('uq_column_mapping_name_version', 'column_mappings', ['name', 'version'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_districts_division_id_divisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts'))
    )
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=True)
    op.create_index(op.f('ix_districts_division_id'), 'districts', ['division_id'], unique=False)
    op.create_table('product_rate_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('benchmark_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('liquidity_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('maker_id', sa.BigInteger(), nullable=True),
    sa.Column('checker_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_product_rate_config_product_period_valid')),
    sa.CheckConstraint('maker_id IS NULL OR checker_id IS NULL OR checker_id <> maker_id', name=op.f('ck_product_rate_config_product_maker_is_not_checker')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_rate_config_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_rate_config'))
    )
    op.create_index(op.f('ix_product_rate_config_product_id'), 'product_rate_config', ['product_id'], unique=False)
    op.create_index('ix_product_rate_lookup', 'product_rate_config', ['product_id', 'effective_from', 'effective_to'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.Column('branch_name', sa.String(length=120), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('METRO', 'URBAN', 'SEMI_URBAN', 'RURAL', name='branch_category'), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('udf', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_branches_district_id_districts')),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_branches_division_id_divisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_branch_code'), 'branches', ['branch_code'], unique=True)
    op.create_index(op.f('ix_branches_district_id'), 'branches', ['district_id'], unique=False)
    op.create_index('ix_branches_division_district', 'branches', ['division_id', 'district_id'], unique=False)
    op.create_index(op.f('ix_branches_division_id'), 'branches', ['division_id'], unique=False)
    op.create_table('upload_batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_ref', sa.String(length=40), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=True),
    sa.Column('column_mapping_id', sa.Integer(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('file_name', sa.String(length=260), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'RECEIVED'"), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('total_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('accepted_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('warned_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('structural_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('supersedes_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('superseded_by_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('committed_by', sa.BigInteger(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculation_run_id', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['column_mapping_id'], ['column_mappings.id'], name=op.f('fk_upload_batches_column_mapping_id_column_mappings')),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], name=op.f('fk_upload_batches_source_system_id_source_systems')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_batches'))
    )
    op.create_index('ix_batch_date_current', 'upload_batches', ['business_date', 'is_current'], unique=False)
    op.create_index('ix_batch_status', 'upload_batches', ['status', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_upload_batches_batch_ref'), 'upload_batches', ['batch_ref'], unique=True)
    op.create_index(op.f('ix_upload_batches_business_date'), 'upload_batches', ['business_date'], unique=False)
    op.create_index(op.f('ix_upload_batches_file_hash'), 'upload_batches', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_batches_file_hash'), table_name='upload_batches')
    op.drop_index(op.f('ix_upload_batches_business_date'), table_name='upload_batches')
    op.drop_index(op.f('ix_upload_batches_batch_ref'), table_name='upload_batches')
    op.drop_index('ix_batch_status', table_name='upload_batches')
    op.drop_index('ix_batch_date_current', table_name='upload_batches')
    op.drop_table('upload_batches')
    op.drop_index(op.f('ix_branches_division_id'), table_name='branches')
    op.drop_index('ix_branches_division_district', table_name='branches')
    op.drop_index(op.f('ix_branches_district_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_branch_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_product_rate_lookup', table_name='product_rate_config')
    op.drop_index(op.f('ix_product_rate_config_product_id'), table_name='product_rate_config')
    op.drop_table('product_rate_config')
    op.drop_index(op.f('ix_districts_division_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index('uq_column_mapping_name_version', table_name='column_mappings')
    op.drop_table('column_mappings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_scope', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_upload_exceptions_batch_id'), table_name='upload_exceptions')
    op.drop_index('ix_exception_severity', table_name='upload_exceptions')
    op.drop_index('ix_exception_batch_rule', table_name='upload_exceptions')
    op.drop_table('upload_exceptions')
    op.drop_index('uq_udf_entity_key', table_name='udf_definitions')
    op.drop_table('udf_definitions')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('ix_staging_batch_status', table_name='staging_account_data')
    op.drop_index('ix_staging_batch_row', table_name='staging_account_data')
    op.drop_index(op.f('ix_staging_account_data_batch_id'), table_name='staging_account_data')
    op.drop_table('staging_account_data')
    op.drop_index(op.f('ix_source_systems_code'), table_name='source_systems')
    op.drop_table('source_systems')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_report_downloads_user_id'), table_name='report_downloads')
    op.drop_index('ix_report_downloads_time', table_name='report_downloads')
    op.drop_table('report_downloads')
    op.drop_index('ix_products_side_active', table_name='products')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_login_audit_username'), table_name='login_audit')
    op.drop_index('ix_login_audit_at', table_name='login_audit')
    op.drop_table('login_audit')
    op.drop_index('ix_global_rate_effective', table_name='global_rate_config')
    op.drop_table('global_rate_config')
    op.drop_index('uq_ftp_results_current_key', table_name='ftp_calculation_results', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_ftp_run', table_name='ftp_calculation_results')
    op.drop_index('ix_ftp_product_date', table_name='ftp_calculation_results', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_ftp_negative', table_name='ftp_calculation_results', postgresql_where=sa.text('is_current AND negative_ftp_flag'))
    op.drop_index('ix_ftp_division_date', table_name='ftp_calculation_results', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_ftp_district_date', table_name='ftp_calculation_results', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_ftp_branch_date', table_name='ftp_calculation_results', postgresql_where=sa.text('is_current'))
    op.drop_table('ftp_calculation_results')
    op.drop_index(op.f('ix_divisions_code'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index('ix_run_status', table_name='calculation_runs')
    op.drop_index('ix_run_dates', table_name='calculation_runs')
    op.drop_index(op.f('ix_calculation_runs_run_ref'), table_name='calculation_runs')
    op.drop_index(op.f('ix_calculation_runs_batch_id'), table_name='calculation_runs')
    op.drop_table('calculation_runs')
    op.drop_index('ix_bank_daily_key', table_name='bank_daily_account_data')
    op.drop_index('ix_bank_daily_batch', table_name='bank_daily_account_data')
    op.drop_table('bank_daily_account_data')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_actor_time', table_name='audit_log')
    op.drop_index('ix_audit_action_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_approval_status', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('agg_daily_product')
    op.drop_table('agg_daily_division')
    op.drop_index(op.f('ix_agg_daily_district_division_id'), table_name='agg_daily_district')
    op.drop_table('agg_daily_district')
    op.drop_table('agg_daily_category')
    op.drop_table('agg_daily_branch_product')
    op.drop_index(op.f('ix_agg_daily_branch_division_id'), table_name='agg_daily_branch')
    op.drop_index(op.f('ix_agg_daily_branch_district_id'), table_name='agg_daily_branch')
    op.drop_table('agg_daily_branch')
    # ### end Alembic commands ###
